### PR TITLE
Fix CSP restrictions

### LINKED ISSUE #13: Not working with Solr 8.5 due to CSP restrictions
Try to run with Solr 8.5 and the GUI won't load due to CSP restrictions:
yasa-solr-csp

### PR DESCRIPTION
**Pull request by kezhenxu94**
closes #13

### CODE REVIEW

**Comment by kezhenxu94** [comment]
I just move the CDN assets into inside the project to avoid loading them from a cross origin urls, the icons should now be displayed correctly

File: yasa-ui/src/style/iconfont/iconfont.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+      (i = null),
+      (c = o.getElementsByTagName('svg')[0]) &&
+        (c.setAttribute('aria-hidden', 'true'),
+        (c.style.position = 'absolute'),
+        (c.style.width = 0),
+        (c.style.height = 0),
+        (c.style.overflow = 'hidden'),
+        (l = c),
+        (a = document.body).firstChild
+          ? ((t = l), (e = a.firstChild).parentNode.insertBefore(t, e))
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.js:42]: Codacy found an issue: [Avoid assignments in operands](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

**Comment by kezhenxu94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 43
           

Complexity increasing per file
==============================
- yasa-ui/src/style/iconfont/iconfont.js  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330&bid=19038285)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-dashboard:before {
+  content: "\e7f8";
+}
+
+.el-icon-yasa-code:before {
+  content: "\e702";
+}
+
+.el-icon-yasa-manage:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:114]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-logging:before {
+  content: "\e64d";
+}
+
+.el-icon-yasa-config:before {
+  content: "\e6db";
+}
+
+.el-icon-yasa-java:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:66]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.js [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+    document.addEventListener
+      ? ~['complete', 'loaded', 'interactive'].indexOf(document.readyState)
+        ? setTimeout(a, 0)
+        : ((t = function () {
+            document.removeEventListener('DOMContentLoaded', t, !1), a();
+          }),
+          document.addEventListener('DOMContentLoaded', t, !1))
+      : document.attachEvent &&
+        ((e = a),
+        (o = c.document),
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.js:54]: Codacy found an issue: [Avoid assignments in operands](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.js [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+        (s = !1),
+        (h = function () {
+          try {
+            o.documentElement.doScroll('left');
+          } catch (c) {
+            return void setTimeout(h, 50);
+          }
+          m();
+        })(),
+        (o.onreadystatechange = function () {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.js:64]: Codacy found an issue: [Avoid assignments in operands](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-bars:before {
+  content: "\e63c";
+}
+
+.el-icon-yasa-logging:before {
+  content: "\e64d";
+}
+
+.el-icon-yasa-config:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:62]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 7]
```diff
@@ -0,0 +1,121 @@
+@font-face {font-family: "iconfont";
+  src: url('iconfont.eot?t=1594114486700'); /* IE9 */
+  src: url('iconfont.eot?t=1594114486700#iefix') format('embedded-opentype'), /* IE6-IE8 */
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:3]: Codacy found an issue: [Expected newline after ":" with a multi-line declaration (declaration-colon-newline-after)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.js [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+      ? ~['complete', 'loaded', 'interactive'].indexOf(document.readyState)
+        ? setTimeout(a, 0)
+        : ((t = function () {
+            document.removeEventListener('DOMContentLoaded', t, !1), a();
+          }),
+          document.addEventListener('DOMContentLoaded', t, !1))
+      : document.attachEvent &&
+        ((e = a),
+        (o = c.document),
+        (s = !1),
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.js:55]: Codacy found an issue: [Avoid assignments in operands](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 9]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-tree:before {
+  content: "\e6e8";
+}
+
+.el-icon-yasa-alias:before {
+  content: "\e68f";
+}
+
+.el-icon-yasa-replica:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:94]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 10]
```diff
@@ -0,0 +1,121 @@
...
+  content: "\e672";
+}
+
+.el-icon-yasa-collections:before {
+  content: "\e623";
+}
+
+.el-icon-yasa-chart:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:102]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 11]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-java:before {
+  content: "\e727";
+}
+
+.el-icon-yasa-solr:before {
+  content: "\e9bf";
+}
+
+.el-icon-yasa-version:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:74]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 12]
```diff
@@ -0,0 +1,121 @@
...
+  url('iconfont.woff?t=1594114486700') format('woff'),
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:5]: Codacy found an issue: [Expected indentation of 4 spaces (indentation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 13]
```diff
@@ -0,0 +1,121 @@
...
+  url('iconfont.ttf?t=1594114486700') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
+  url('iconfont.svg?t=1594114486700#iconfont') format('svg'); /* iOS 4.1- */
+}
+
+.iconfont {
+  font-family: "iconfont" !important;
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:11]: Codacy found an issue: [Unexpected missing generic font family (font-family-no-missing-generic-family-keyword)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 14]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-doc:before {
+  content: "\e788";
+}
+
+.el-icon-yasa-email:before {
+  content: "\e712";
+}
+
+.el-icon-yasa-bug:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:26]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 15]
```diff
@@ -0,0 +1,121 @@
...
+
+.iconfont {
+  font-family: "iconfont" !important;
+  font-size: 16px;
+  font-style: normal;
+  -webkit-font-smoothing: antialiased;
+  -moz-osx-font-smoothing: grayscale;
+}
+
+.el-icon-yasa-doc:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:18]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 16]
```diff
@@ -0,0 +1,121 @@
...
...s67EJjdYMtVk6L1wSTK+Z55nIqm4yDVhu0v+a0YXM0lb1PvVWVokklbWptnYT6+BmVk3t+q1TwapF8zX6lPGRKh2z+3Nix57Vf8nkgPpH7Okf6Zjt27SZb+dP3aSO5n2/AqFV1Y457uFX4KfgcJqDEHBNZRRp1J16ZbNOtD0rBpk4YXri9Zd+0/5SkZ7R9+bznjj0vYsUcYI5/YVBhXVB3//Gp/dERsuzIO4nEhnoHks6EhJe0GEcbrRp87LmPocTpkIzodc0nPn+0zoGsu7TXIPN7jh0/OpL3x9amlg+9L1oJQnQ4VtR6dexyV2+QRhuHG2yyQzDIlHaF2wyjTIOF4k6/BJmwue78flu81vYcrm5N0MMmtXLrCyPhevY+fz5biBeOPsgmD0jGWMCAGD96LSjbrmMZaqqGWswAyp6E/2OyeOoCEP+y2sUO4q+BZj9IxpDWWPB6MdgtilqxSTZibXoZ3XafSwQ6pKjmBeq7ujArEzRteiA2jGGwayISHDQZoXZFuwh1ggzWefQk/ajKi0OQV8AzLZhPy1QNR+1YbQRyabAw9q6Nofu/4VA/uey7PYQwSDj/Y5uSqJAgJMsAQRgtBHwB70F8Nt0kWOIW5+ZdzV402lw8+wsUiH2gbcYwtkRKvv0gCRvABhZ3K4B91hA29oZgw1oJwyFOWDMMCCAlYFLcWJ4IIM7UwMCBDESOEJE92TQhGrAAMERAcABljoMAQbsZyjQYJRhwIAJA5dyl+FBB94wNWAgGCMBF9H0SYa7bD5Wb0pg5F33dBmlBDfPVtG+3xSvDJpOVwv+SVsuc4ftPl/7RYW0j3baLR7Nggsqvft0Xo2YxVWVM6Ftk1k97XaBaneL0g9WgzclsGBF73TPTTNKCXe2VeHXf1O8MqjhlJtN/0lbfnznYGtvYXyJYnXKUzm43eKRMRWcMNtbeueTSWJZJU6lGzsT2lZqoerJjl0q2Irt4QP9+yE8facVL3YNoWFg4eARQAjiP639LkOO4nA8nS/X2/3xfL0Ze8Ep9ZB53F3j5E08TRJxnXSAl+VL5EJUSafIcvWTyvAkG9I2Z4kxlzh7xF3kODnDDSZNWOe3J8Bj1p7NqF/kEr4TFKSJKdEUOEObK1XOCGsU5ofOLWNpU0ygtvTQUiegfoJHoZ/1UCDS0ueG0mfkORgAAAAA') format('woff2'),
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:4]: Codacy found an issue: [Expected indentation of 4 spaces (indentation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 17]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-Code:before {
+  content: "\e67c";
+}
+
+.el-icon-yasa-help:before {
+  content: "\e65b";
+}
+
+.el-icon-yasa-back:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:38]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 18]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-code:before {
+  content: "\e702";
+}
+
+.el-icon-yasa-manage:before {
+  content: "\e675";
+}
+
+.el-icon-yasa-discovery:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:118]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 19]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-bug:before {
+  content: "\e630";
+}
+
+.el-icon-yasa-Code:before {
+  content: "\e67c";
+}
+
+.el-icon-yasa-help:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:34]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 20]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-version:before {
+  content: "\e738";
+}
+
+.el-icon-yasa-system:before {
+  content: "\e608";
+}
+
+.el-icon-yasa-instance:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:82]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 21]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-help:before {
+  content: "\e65b";
+}
+
+.el-icon-yasa-back:before {
+  content: "\e6d8";
+}
+
+.el-icon-yasa-zookeeper:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:42]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 22]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-email:before {
+  content: "\e712";
+}
+
+.el-icon-yasa-bug:before {
+  content: "\e630";
+}
+
+.el-icon-yasa-Code:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:30]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 23]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-instance:before {
+  content: "\e613";
+}
+
+.el-icon-yasa-tree:before {
+  content: "\e6e8";
+}
+
+.el-icon-yasa-alias:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:90]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.css [hunk 24]
```diff
@@ -0,0 +1,121 @@
...
+
+.el-icon-yasa-zookeeper:before {
+  content: "\e771";
+}
+
+.el-icon-yasa-cloud:before {
+  content: "\e7be";
+}
+
+.el-icon-yasa-play:before {
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.css:50]: Codacy found an issue: [Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation)](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

File: yasa-ui/src/style/iconfont/iconfont.js [hunk 25]
```diff
@@ -0,0 +1,67 @@
...
+    (o.innerHTML = i),
+      (i = null),
+      (c = o.getElementsByTagName('svg')[0]) &&
+        (c.setAttribute('aria-hidden', 'true'),
+        (c.style.position = 'absolute'),
+        (c.style.width = 0),
+        (c.style.height = 0),
+        (c.style.overflow = 'hidden'),
+        (l = c),
+        (a = document.body).firstChild
```
Comment (kezhenxu94) [inline yasa-ui/src/style/iconfont/iconfont.js:41]: Codacy found an issue: [Avoid assignments in operands](https://app.codacy.com/gh/yasa-org/yasa/pullRequest?prid=5815330)

**Comment by kezhenxu94** [comment]
Generated files will be ignored next time in Codacy

**Comment by kezhenxu94** [comment]
@chatman thanks for verifying 😄
